name: Auto-Update Portal
on:
  schedule:
    - cron: "0 6 * * *"  # Daily at 6 AM
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download and Update Portal
        run: |
          # Download latest portal
          curl -o assets/built/portal.min.js "https://cdn.jsdelivr.net/gh/somos-criptonautas/ghost-portal-mirror/portal.min.js"
          
          # Apply your customizations (replace "jamie" with your name)
          sed -i 's/jamie/YourName/g' assets/built/portal.min.js
          
      - name: Deploy to Ghost
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
